export const mockAccordionData = [
  {
    title: "Accordion Item #1",
    body: "This is the first item's accordion body. It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "Accordion Item #2",
    body: "This is the second item's accordion body. It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "Accordion Item #3",
    body: "This is the third item's accordion body. It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
];

export const commentsDetails = [
  {
    username: "Amit Roy",
    comment: "this is some random comment1",
    replies: [
      {
        username: "Bibhuti Bhushan",
        comment: "1st reply on comment 1",
        replies: [
          {
            username: "John Doe",
            comment: "1st reply on comment 1",
            replies: [
              {
                username: "Rakesh Ghosh",
                comment: "1st nested reply on comment 1",
                replies: [
                  {
                    username: "Rakesh Ghosh",
                    comment: "1st nested reply on comment 1",
                  },
                  {
                    username: "Sujoy dey",
                    comment: "2nd nested reply on comment 1",
                  },
                ],
              },
              {
                username: "Sujoy dey",
                comment: "2nd nested reply on comment 1",
              },
            ],
          },
          { username: "Tulika das", comment: "2nd reply on comment 1" },
        ],
      },
      { username: "Jewel Dey", comment: "2nd reply on comment 1" },
    ],
  },
  {
    username: "Johnny Braistow",
    comment: "this is some random comment2",
    replies: [
      {
        username: "Bibhuti Bhushan",
        comment: "1st reply on comment 2",
        replies: [
          { username: "Bibhuti Bhushan", comment: "1st reply on comment 2" },
          { username: "Tulika das", comment: "2nd reply on comment 2" },
        ],
      },
      {
        username: "Tulika das",
        comment: "2nd reply on comment 2",
        replies: [
          {
            username: "Bibhuti Bhushan",
            comment: "1st reply on comment 2",
            replies: [
              {
                username: "Bibhuti Bhushan",
                comment: "1st reply on comment 2",
              },
              {
                username: "Tulika das",
                comment: "2nd reply on comment 2",
                replies: [
                  {
                    username: "Bibhuti Bhushan",
                    comment: "1st reply on comment 2",
                  },
                  { username: "Tulika das", comment: "2nd reply on comment 2" },
                ],
              },
            ],
          },
          { username: "Tulika das", comment: "2nd reply on comment 2" },
        ],
      },
    ],
  },
  {
    username: "Brain Lara",
    comment: "this is some random comment3",
    replies: [
      { username: "Bibhuti Bhushan", comment: "1st reply on comment 3" },
      { username: "Tulika das", comment: "2nd reply on comment 3" },
    ],
  },
  {
    username: "Abhinabh Majahn",
    comment: "this is some random comment4",
    replies: [
      { username: "Bibhuti Bhushan", comment: "1st reply on comment 4" },
      { username: "Tulika das", comment: "2nd reply on comment 4" },
    ],
  },
];

export const imageSliderData = [
  "https://images.unsplash.com/photo-1721023672487-906b07479bff?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwzfHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1709148910322-5a58adaf0e9d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwyfHx8ZW58MHx8fHx8",
  "https://images.unsplash.com/photo-1720968678641-743d61f1bc52?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1720975070354-60e7ec072312?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1720791543614-2ffe0fe46263?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw0OHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1718554517780-b9ca6513c4c3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHw2Nnx8fGVufDB8fHx8fA%3D%3D",
];

var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

export const generateRandomName = () => {
  let fullName = nameList[Math.floor(Math.random() * nameList.length)];
  return fullName;
};

export const liveChatData = [
  {
    id: 0,
    name: generateRandomName(),
    imageURL:
      "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
    message: "Something useful",
  },
  // {
  //   id: 1,
  //   name: "Joy Biswas",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 2,
  //   name: "Chumki Debnath",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 3,
  //   name: "Saritha Chatterjee",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 0,
  //   name: "Amit Roy",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 1,
  //   name: "Joy Biswas",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 2,
  //   name: "Chumki Debnath",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 3,
  //   name: "Saritha Chatterjee",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 0,
  //   name: "Amit Roy",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 1,
  //   name: "Joy Biswas",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 2,
  //   name: "Chumki Debnath",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
  // {
  //   id: 3,
  //   name: "Saritha Chatterjee",
  //   imageURL:
  //     "https://yt4.ggpht.com/rREYRLtk9IOU0E9gzmA6JqP5pPeRkHBBuxkEJweb5HcTiermVVa6ygW8ZseF3sluE5NkrcAPb7M=s32-c-k-c0x00ffffff-no-rj",
  //   message: "Something useful",
  // },
];
